### ISSUE TITLE
Unable to Advertise Server in Public Browser

### ISSUE THREAD

**Issue by eroc1990** [ellitedev/srb2kart-server-docker#2]
Sorry if this isn't the place to ask this, so feel free to close this issue if not relevant.

How do you set your server to publicly advertise from either the cfg or from extra parameters? I'm unable to get my server to show up in the browser under your image.

**Comment by ellitedev** [comment]
Hey! Thx for reaching out.
You can set `advertise` to `1` in the `kartserv.cfg` file that you place in the [config volume](https://github.com/ellitedev/srb2kart-server-docker#config) that you can mount.

The server config file is basically a list of commands to be ran.

Here's two wiki entries that could explain more about the server config file:
- [SRB2 Console Commands](https://wiki.srb2.org/wiki/Console/Commands)
- [SRB2 Kart Specific Console Commands](https://wiki.srb2.org/wiki/User:ThatAwesomeGuy173/SRB2Kart/Commands)

I also highly suggest joining the KartKrew [Discord](https://discord.gg/7bdPz5gHbx), and asking for help in there, there's some really smart people there.

Let me know if that helped!

**Comment by eroc1990** [comment]
That was all it was. Thanks! I had tried to configure `room 33` in my `kartserv.cfg` file but that didn't do it. This did.

Thanks again for putting together and maintaining this container image.
